<a href="https://colab.research.google.com/github/cbonnin88/VoltShift/blob/main/VoltShift_data_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# **Generate Users Data**

In [ ]:
np.random.seed(42)
num_users = 1000

In [ ]:
countries = ['France','Germany','The Netherlands']
genders = ['Male','Female','Non-Binary']
tiers = ['Free','Basic','Premium']
price_map = {
    'Free':0.00,
    'Basic':3.99,
    'Premium':9.99
    }

In [ ]:
country_data = np.random.choice(countries, num_users, p=[0.5,0.3,0.2])
gender_data = np.random.choice(genders, num_users, p=[0.48,0.48,0.04])
tier_data = np.random.choice(tiers, num_users, p=[0.75,0.18,0.07])
price_data = [price_map[tier] for  tier in tier_data]

In [ ]:
age_data = np.clip(np.random.normal(loc=32,scale=9,size=num_users),18,70).astype(int)

In [ ]:
users = {
    'user_id': range(1,num_users + 1),
    'country': country_data,
    'gender': gender_data,
    'age': age_data,
    'plan_tier': tier_data,
    'plan_price': price_data,
    'join_date': [datetime(2024,1,1)+ timedelta(days=random.randint(0,180)) for _ in range(num_users)]
}

In [ ]:
df_users = pd.DataFrame(users)
df_users.to_csv('users.csv',index=False)

In [ ]:
display(df_users.head())

   user_id          country  gender  age plan_tier  plan_price  join_date
0        1           France    Male   41      Free        0.00 2024-06-21
1        2  The Netherlands  Female   37      Free        0.00 2024-02-11
2        3          Germany  Female   38     Basic        3.99 2024-03-22
3        4          Germany  Female   19      Free        0.00 2024-05-15
4        5           France  Female   42      Free        0.00 2024-03-30

# **Generate Trips Data**

In [ ]:
trips = []
modes = ['Bike','Train','EV']
co2_savings_per_km = {'Bike':0.2,'Train':0.15,'EV':0.1}

In [ ]:
for _, user in df_users.iterrows():
  num_early_trips = random.randint(5,20)
  for _ in range(num_early_trips):
    trip_date = user['join_date'] + timedelta(days=random.randint(1,21))
    mode = random.choice(modes)
    distance = round(random.uniform(2,30),1)
    trips.append([user['user_id'], trip_date, mode,distance, distance * co2_savings_per_km[mode]])

  retention_chance = 0.8 if user['plan_tier'] == 'Free' else 0.6

  if random.random() > retention_chance:
    num_late_trips = random.randint(5,15)
    for _ in range(num_late_trips):
      trip_date = user['join_date'] + timedelta(days=random.randint(31,90))
      mode = random.choice(modes)
      distance = round(random.uniform(2,30),1)
      trips.append([user['user_id'], trip_date,mode, distance, distance * co2_savings_per_km[mode]])

In [ ]:
df_trips = pd.DataFrame(trips, columns=['user_id','trip_date','transport_mode','distance_km','co2_saved_kg'])
df_trips.to_csv('trips.csv',index=False)

display(df_trips.head())

   user_id  trip_date transport_mode  distance_km  co2_saved_kg
0        1 2024-06-30             EV         27.2         2.720
1        1 2024-07-08          Train         28.4         4.260
2        1 2024-06-22          Train         17.5         2.625
3        1 2024-06-29           Bike         14.5         2.900
4        1 2024-06-22             EV         16.8         1.680